import Head from "next/head";
import styles from "@/styles/Home.module.css"; // olhar a sintaxe de como importa um css no pdf.
// acima mostra que está importando da pasta styles, o arquivo home.module.css. entao chamar as classes neste arquivo e estilizar.

export default function Home() {
  return (
    <div>
      <Head>
        <title>Primeira página</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <header className={styles.header}>
          <h1>React JS</h1>
        </header>
        <main>
          <section className={styles.titulos}>
            <h1>React JS</h1>
            <p>Biblioteca Javascript para criar SPAs</p>
            <button>
              <a>Site Oficial</a>
            </button>
          </section>
          <section className={styles.requisitos}>
            <h2>Requisitos</h2>
            <p>Veja abaixo os requisitos mínimos para aprender React.JS</p>
            <div className={styles.grid}>
              <div className={styles.box}>
                <h3>HTML</h3>
                <p>Aprender a estruturar os eementos da página com HTML</p>
              </div>
              <div className={styles.box}>
                <h3>CSS</h3>
                <p>Aprender a estilizar os elementos da página com CSS</p>
              </div>
              <div className={styles.box}>
                <h3>Javascript</h3>
                <p>Aprender a linguagem utilizada pelo ReactJS, o Javascript</p>
              </div>
            </div>
          </section>
        </main>
        <footer className={styles.footer}>
          <p>Curso de Introdução ao ReactJS</p>
        </footer>
      </div>
    </div>
  );
}
